### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by phadej**
These are the changes as in #48.

I think we should include them, as they would make the release a little more solid.

Also I regenerated `.travis.yml` with newer `haskell-ci` (the successor of `make_travis_yml2.hs`).

### CODE REVIEW

**Comment by ezrakilty** [comment]
Great—I'm going to let the Travis tests complete and then I'll merge it and release it.

In case anything goes wrong with the Template Haskell changes, I'll still update the version number and re-release.

**Comment by ezrakilty** [comment]
OK, I'm ready to release: https://hackage.haskell.org/package/network-uri-2.6.2.0/candidate

I've never had to unrelease a package before. Is there anything I have to do to  suppress 2.7.0.0 from being picked up by anyone?

**Comment by ezrakilty** [comment]
Released 2.6.2.0

**Comment by ezrakilty** [comment]
OK, I found the tool to set deprecated versions in Hackage and deprecated 2.7.0.0.

FYI: I'm going to be mostly offline for the next few days (great timing, I know). I maybe be able to follow the thread, but not update the code.

**Comment by phadej** [comment]
Yes, deprecation is the right thing to do, thanks for prompt responses now! I think it's fine now.

**Pull request merged**
